version: '{branch}--{build}'

platform:
  - x64

environment:

  matrix:
    # windows python 3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON_VERSION: "3.7"
      MINICONDA: C:\Miniconda3
      PYTHON_ARCH: "64"


# stack: python %PYTHON%

build: off

init:
  - cmd: "ECHO %PYTHON_VERSION% %MINICONDA%"

install:

  - SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %PATH%

  - cmd: conda config --set always_yes yes
  - cmd: conda update -q conda
  - cmd: conda info -a
  - cmd: "conda create -q -n test-environment python=%PYTHON_VERSION% pyinstaller"
  - cmd: activate test-environment
  
  # check that the correct python version is being used
  - cmd: "python --version"

  # enforce the latest version of pip
  - cmd: "python -m pip install --upgrade pip"

  # build
  - cmd: "pyinstaller --onefile app/app.py"

artifacts:
  - path: 'dist\app*'
    name: app
