version: '{branch}--{build}'

platform:
  - x64

environment:

  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\run_with_env.cmd"

  matrix:
    # windows python 3.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "3.7"
      PYTHON_ARCH: "64"
      PY_DIR: C:\Python37-x64


# stack: python %PYTHON%

build: off

install:

  - cmd: set PATH=%PY_DIR%;%PY_DIR\Scripts;%PATH%

  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

  # check that the correct python version is being used
  - cmd: "python --version"

  # enforce the latest version of pip
  - cmd: "python -m pip install --upgrade pip"

  # install build dependencies
  - cmd: "python -m pip install -r requirements_dev.txt"

  # build
  - cmd: "python -m pyinstaller --onefile app/app.py"

artifacts:
  - path: 'dist\app*'
    name: app
