image:
  - Ubuntu
  # - Visual Studio 2019
  # - macos

stack: python 3.7

version: '{branch}--{build}'

environment:

  PY_DIR: C:\Python37-x64

  matrix:
    - TOXENV: py37
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%;%PATH%

build: off

install:

  # check that the correct python version is being used
  - "python --version"

  # enforce the latest version of pip
  - "python -m pip install --upgrade pip"

  # install build dependencies
  - "python -m pip install -r requirements_dev.txt"

  # build
  - "python setup.py build"

deploy:
  release: appveyor-test-v$(APPVEYOR_BUILD_VERSION)
  description: 'New release'
  provider: GitHub
  artifact:
    path: build
    name: app
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
