image:
  - Ubuntu

version: '{branch}--{build}'

platform:
  - x64

environment:
  # PY_DIR: C:\Python37-x64

  matrix:
    # ubuntu python 2.7
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "2.7"
      PYTHON_ARCH: "64"

    # ubuntu python 3
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.6"
      PYTHON_ARCH: "64"


stack: python %PYTHON%

init:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%;%PATH%

build: off

install:

  # check that the correct python version is being used
  - "python --version"

  # enforce the latest version of pip
  - "python -m pip install --upgrade pip"

  # install build dependencies
  - "python -m pip install -r requirements_dev.txt"

  # build
  - "pyinstaller --onefile app/app.py"

artifacts:
  - path: 'dist\app*'
    name: app
