image:
  - Ubuntu

version: '{branch}--{build}'

environment:

  matrix:
    - TOXENV: py37
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      PYTHON: "$HOME/venv3.8.2"

install:

  - "echo %PYTHON%"

  # check that the correct python version is being used
  - "%PYTHON%/python --version"

  # enforce the latest version of pip
  - "%PYTHON%/python -m pip install --upgrade pip"

  # install build dependencies
  - "%PYTHON%/python -m pip install -r requirements_dev.txt"

  # build
  - "%PYTHON%/python -m python setup.py build"
